version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/base:2021.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Security Test
          command: |
            docker pull armourzero/pipe-scan:latest
            docker create --name azscan armourzero/pipe-scan:latest \
              --apikey="$AZ_TOKEN" \
              --projectkey="ShqmGdSQKGrlXBqASjRGUWrpistVvOrd" \
              --branch="$CIRCLE_BRANCH" \
              --repo="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
            docker cp . azscan:/app/wrk
            docker start -a azscan

workflows:
  version: 2
  az_security_test:
    jobs:
      - build_and_test
